### ISSUE TITLE
motor example

### ISSUE THREAD

**Issue by bbartling** [amogorkon/fuzzylogic#6]
Hi Anselm !

I am finally getting around to delving back into this stuff... On the previous git issue you had this code for a motor example. Can I get a tip on what to import? I dont think I have the entry point stuff correct:

```
from fuzzylogic import classes, functions
from fuzzylogic import very
```

Entire script:

```
from fuzzylogic import classes, functions
from fuzzylogic import very

temp = classes.Domain("Temperature", -80, 80)
hum = classes.Domain("Humidity", 0, 100)
motor = classes.Domain("Speed", 0, 2000)

temp.cold = functions.S(0,20)
temp.hot = functions.R(15,30)

hum.dry = functions.S(20,50)
hum.wet = functions.R(40,70)

motor.fast = functions.R(1000,1500)
motor.slow = ~motor.fast

R1 = classes.Rule({(temp.hot, hum.dry): motor.fast})
R2 = classes.Rule({(temp.cold, hum.dry): very(motor.slow)})
R3 = classes.Rule({(temp.hot, hum.wet): very(motor.fast)})
R4 = classes.Rule({(temp.cold, hum.wet): motor.slow})

Rules = classes.Rule({(temp.hot, hum.dry): motor.fast,
                      (temp.cold, hum.dry): very(motor.slow),
                      (temp.hot, hum.wet): very(motor.fast),
                      (temp.cold, hum.wet): motor.slow,
                      })

Rules == R1 | R2 | R3 | R4 == sum([R1, R2, R3, R4])

print(Rules(hum(30), temp(9)))

```

**Comment by amogorkon** [comment]
Hey Ben,

the functions very, plus and minus are called "fuzzylogic hedges" or "linguistic hedges", so you can find them in fuzzylogic.hedges :-)

**Comment by amogorkon** [comment]
Also, if you don't need to hot-reload the module (which I doubt in this case), I would advice to "from fuzzylogic.classes import Domain, Set, Rule" - it's just three things to import from there but you save a lot of typing afterwards.. but that's a matter of taste, I guess?

**Comment by bbartling** [comment]
Thanks for the quick response! For some reason I cant get this to work `from fuzzylogic.classes import Domain, Set, Rule` in a script .py file.

Sorry most likely noob related. Is python 3.7 Ok or what version would you recommend?

Trying the command prompt instead of script, I can `import fuzzylogic` and `from fuzzylogic.classes import Domain` but it seems to error out after that.

```
C:\Users\bbartling>py -3.7
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fuzzylogic
>>> from fuzzylogic.classes import Domain
>>> from fuzzylogic.classes import Domain, Set, Rule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Rule' from 'fuzzylogic.classes' (C:\Users\bbartling\AppData\Local\Programs\Python\Python37\lib\site-packages\fuzzylogic\classes.py)
>>> from fuzzylogic import very
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'very' from 'fuzzylogic' (C:\Users\bbartling\AppData\Local\Programs\Python\Python37\lib\site-packages\fuzzylogic\__init__.py)
>>>
```

I also did a `pip install fuzzylogic --upgrade` too:
```
Successfully built fuzzy logic
Installing collected packages: fuzzy, toolz, multipledispatch, unification, logic
Successfully installed fuzzy-1.2.2 logic-0.2.3 multipledispatch-0.6.0 toolz-0.11.1 unification-0.2.2
```

**Comment by amogorkon** [comment]
wait, wait, wait.. there are two issues here. and the second one is very strange.

**Comment by amogorkon** [comment]
This is what I get when I install fuzzylogic:

python -m pip install fuzzylogic
Collecting fuzzylogic
  Downloading fuzzylogic-1.0.0.tar.gz (20 kB)
Building wheels for collected packages: fuzzylogic
  Building wheel for fuzzylogic (setup.py) ... done
  Created wheel for fuzzylogic: filename=fuzzylogic-1.0.0-py3-none-any.whl size=16507 sha256=a0a03738134f5d8a34147e3647261cc93d068ade2e0f5e01e8bef7266a45119c
  Stored in directory: /home/thorsten/.cache/pip/wheels/53/5d/16/b679f2376a040a679e1b539d9d7dc97777cd6c4a375916102b
Successfully built fuzzylogic
Installing collected packages: fuzzylogic
Successfully installed fuzzylogic-1.0.0

**Comment by amogorkon** [comment]
I also can easily import Domain and Set from fuzzylogic.classes, but I get a similar error when I try to import Rule :-/

**Comment by amogorkon** [comment]
Try to `from fuzzylogic.hedges import very`, that should work

**Comment by bbartling** [comment]
I may officially jump too python 3.9

```
C:\Users\bbartling>py -3.9 -m pip install fuzzylogic
Collecting fuzzylogic
  Downloading fuzzylogic-1.0.0.tar.gz (20 kB)
Using legacy 'setup.py install' for fuzzylogic, since package 'wheel' is not installed.
Installing collected packages: fuzzylogic
    Running setup.py install for fuzzylogic ... done
Successfully installed fuzzylogic-1.0.0
```

**Comment by amogorkon** [comment]
I don't see a reason why there may be a problem with lower py3 versions, but okay.. and if you can use py39, I'd even recommend it, there are pretty nice features and no drawbacks I'm aware of (it'll become default on Ubuntu this month even afaik).

**Comment by amogorkon** [comment]
Hmm.. you need to be careful with your python environments also if you're on windows. I personally use VMs to seperate my stuff, but a lot of people recommend using env.

**Comment by amogorkon** [comment]
I'm still baffled why your previous install cmd resulted in 
```
Installing collected packages: fuzzy, toolz, multipledispatch, unification, logic
Successfully installed fuzzy-1.2.2 logic-0.2.3 multipledispatch-0.6.0 toolz-0.11.1 unification-0.2.2
```

**Comment by bbartling** [comment]
Now I am running into numpy issue with py39, jumping back to py37

run this on python 3.7:
```
from fuzzylogic.classes import Domain, Set, Rule
from fuzzylogic.hedges import very

temp = classes.Domain("Temperature", -80, 80)
hum = classes.Domain("Humidity", 0, 100)
motor = classes.Domain("Speed", 0, 2000)

temp.cold = functions.S(0,20)
temp.hot = functions.R(15,30)

hum.dry = functions.S(20,50)
hum.wet = functions.R(40,70)

motor.fast = functions.R(1000,1500)
motor.slow = ~motor.fast

R1 = classes.Rule({(temp.hot, hum.dry): motor.fast})
R2 = classes.Rule({(temp.cold, hum.dry): very(motor.slow)})
R3 = classes.Rule({(temp.hot, hum.wet): very(motor.fast)})
R4 = classes.Rule({(temp.cold, hum.wet): motor.slow})

Rules = classes.Rule({(temp.hot, hum.dry): motor.fast,
                      (temp.cold, hum.dry): very(motor.slow),
                      (temp.hot, hum.wet): very(motor.fast),
                      (temp.cold, hum.wet): motor.slow,
                      })

Rules == R1 | R2 | R3 | R4 == sum([R1, R2, R3, R4])

print(Rules(hum(30), temp(9)))
```
Just running this in IDLE:
```
>>> 
= RESTART: C:\Users\bbartling\OneDrive - Slipstream\Desktop\fuzzyStuff\test_new.py
Traceback (most recent call last):
  File "C:\Users\bbartling\OneDrive - Slipstream\Desktop\fuzzyStuff\test_new.py", line 1, in <module>
    from fuzzylogic.classes import Domain, Set, Rule
  File "C:\Users\bbartling\AppData\Local\Programs\Python\Python37\lib\site-packages\fuzzylogic\classes.py", line 420
    if (x := min(actual_values[k] for k in K if k in actual_values)) > 0]
          ^
SyntaxError: invalid syntax
>>> 
```

**Comment by bbartling** [comment]
I dont know enough about walrus operator

**Comment by amogorkon** [comment]
Ahhh! The walrus operator was introduced in Python 3.8 ;-D

**Comment by bbartling** [comment]
Ha, I have an anaconda version 3.8 maybe ill try this :)

**Comment by amogorkon** [comment]
If you need py37, I can expand the expression and make sure it works with that version.

**Comment by bbartling** [comment]
No need for py37

So trying the code in Jupiter lab IPython 3.8, I seem to have this issue:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-cbca75fd6930> in <module>
----> 1 from fuzzylogic.classes import Domain, Set, Rule
      2 from fuzzylogic.hedges import very
      3 
      4 temp = classes.Domain("Temperature", -80, 80)
      5 hum = classes.Domain("Humidity", 0, 100)

~\Anaconda\lib\site-packages\fuzzylogic\classes.py in <module>
     11 import numpy as np
     12 
---> 13 from combinators import MAX, MIN, bounded_sum, product, simple_disjoint_sum
     14 from functions import inv, normalize
     15 

ModuleNotFoundError: No module named 'combinators'
```

**Comment by bbartling** [comment]
I pip installed `combinators` which seemed to work

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cbca75fd6930> in <module>
----> 1 from fuzzylogic.classes import Domain, Set, Rule
      2 from fuzzylogic.hedges import very
      3 
      4 temp = classes.Domain("Temperature", -80, 80)
      5 hum = classes.Domain("Humidity", 0, 100)

~\Anaconda\lib\site-packages\fuzzylogic\classes.py in <module>
     11 import numpy as np
     12 
---> 13 from combinators import MAX, MIN, bounded_sum, product, simple_disjoint_sum
     14 from functions import inv, normalize
     15 

ImportError: cannot import name 'MAX' from 'combinators' (C:\Users\bbartling\Anaconda\lib\site-packages\combinators\__init__.py)
```

**Comment by amogorkon** [comment]
Did you mean fuzzylogic.combinators? ;)

**Comment by amogorkon** [comment]
Wait, what?

**Comment by amogorkon** [comment]
fuzzylogic.combinators is just a submodule, there is nothing to be pip installed

**Comment by amogorkon** [comment]
I think by installing an extra combinators package, you broke fuzzylogic (which shouldn't happen, I'm not sure if relative imports would work better here)

**Comment by amogorkon** [comment]
Hey, at least you found a few nice bugs that are worth looking into ;p

**Comment by bbartling** [comment]
Ha sounds good let me know if you have any tips to get it working ;)

**Comment by amogorkon** [comment]
Something is very wrong here. Strange I haven't stumbled over those issues when I tested the release, but now I'm getting hit by all kinds of problems like you are. I'll look into it later/tomorrow.

**Comment by amogorkon** [comment]
I need to update my tests to cover all new stuff.. 
I've still got an import problem on Thonny, but I'm guessing that's not related to this. My standalone tests on a vanilla VM work just fine. I updated the requirements to 3.8 to avoid confusion.

**Comment by bbartling** [comment]
```
from fuzzylogic.classes import Domain, Set, Rule
from fuzzylogic.hedges import very

temp = classes.Domain("Temperature", -80, 80)
hum = classes.Domain("Humidity", 0, 100)
motor = classes.Domain("Speed", 0, 2000)

temp.cold = functions.S(0,20)
temp.hot = functions.R(15,30)

hum.dry = functions.S(20,50)
hum.wet = functions.R(40,70)

motor.fast = functions.R(1000,1500)
motor.slow = ~motor.fast

R1 = classes.Rule({(temp.hot, hum.dry): motor.fast})
R2 = classes.Rule({(temp.cold, hum.dry): very(motor.slow)})
R3 = classes.Rule({(temp.hot, hum.wet): very(motor.fast)})
R4 = classes.Rule({(temp.cold, hum.wet): motor.slow})

Rules = classes.Rule({(temp.hot, hum.dry): motor.fast,
                      (temp.cold, hum.dry): very(motor.slow),
                      (temp.hot, hum.wet): very(motor.fast),
                      (temp.cold, hum.wet): motor.slow,
                      })

Rules == R1 | R2 | R3 | R4 == sum([R1, R2, R3, R4])

print(Rules(hum(30), temp(9)))
```

**Comment by amogorkon** [comment]
if you import "from fuzzylogic.classes import ..", there is no name "classes" assigned, just use "Domain" and "Rule" directly in your script :)

**Comment by bbartling** [comment]
Ok, so I made some modifications, thanks for the tips btw:

```
from fuzzylogic.classes import Domain, Set, Rule
from fuzzylogic.hedges import very

temp = Domain("Temperature", -80, 80)
hum = Domain("Humidity", 0, 100)
motor = Domain("Speed", 0, 2000)

temp.cold = functions.S(0,20)
temp.hot = functions.R(15,30)

hum.dry = functions.S(20,50)
hum.wet = functions.R(40,70)

motor.fast = functions.R(1000,1500)
motor.slow = ~motor.fast

R1 = Rule({(temp.hot, hum.dry): motor.fast})
R2 = Rule({(temp.cold, hum.dry): very(motor.slow)})
R3 = Rule({(temp.hot, hum.wet): very(motor.fast)})
R4 = Rule({(temp.cold, hum.wet): motor.slow})

Rules = Rule({(temp.hot, hum.dry): motor.fast,
                      (temp.cold, hum.dry): very(motor.slow),
                      (temp.hot, hum.wet): very(motor.fast),
                      (temp.cold, hum.wet): motor.slow,
                      })

Rules == R1 | R2 | R3 | R4 == sum([R1, R2, R3, R4])

print(Rules(hum(30), temp(9)))
```

When I run this I get an error Windows py39:
```
Traceback (most recent call last):
  File "C:\Users\bbartling\OneDrive - Slipstream\Desktop\fuzzyStuff\test_new.py", line 8, in <module>
    temp.cold = functions.S(0,20)
NameError: name 'functions' is not defined
```

**Comment by amogorkon** [comment]
you didn't import functions ;p

**Comment by bbartling** [comment]
Got it... So with importing `functions` the code doesnt error out but print statement at the end of the script:

`print(Rules(hum(45), temp(22)))`

Just prints:

`None`

Ill also try this on Linux too here sometime soon.

```
from fuzzylogic.classes import Domain, Set, Rule
from fuzzylogic.hedges import very
from fuzzylogic import functions

temp = Domain("Temperature", -80, 80)
hum = Domain("Humidity", 0, 100)
motor = Domain("Speed", 0, 2000)

temp.cold = functions.S(0,20)
temp.hot = functions.R(15,30)

hum.dry = functions.S(20,50)
hum.wet = functions.R(40,70)

motor.fast = functions.R(1000,1500)
motor.slow = ~motor.fast

R1 = Rule({(temp.hot, hum.dry): motor.fast})
R2 = Rule({(temp.cold, hum.dry): very(motor.slow)})
R3 = Rule({(temp.hot, hum.wet): very(motor.fast)})
R4 = Rule({(temp.cold, hum.wet): motor.slow})

Rules = Rule({(temp.hot, hum.dry): motor.fast,
                      (temp.cold, hum.dry): very(motor.slow),
                      (temp.hot, hum.wet): very(motor.fast),
                      (temp.cold, hum.wet): motor.slow,
                      })

Rules == R1 | R2 | R3 | R4 == sum([R1, R2, R3, R4])

print(Rules(hum(45), temp(22)))
```

**Comment by amogorkon** [comment]
Well, that's no surprise - Rule.__call__ expects a dictionary of {domain: value}, and 
```
            if not weights:
                return None
```
so...
if you change your code to
print(Rules({hum: 45, temp: 22}))

**Comment by bbartling** [comment]
Sweet it works!
```

1633.939042858428
>>> 
```
It maybe a couple more weeks before I bug you again :) I am working on creating "[agents](https://volttron.readthedocs.io/en/develop/developing-volttron/developing-agents/agent-development.html)" (drivers) for this platform. I've never done this before so the results should be real interesting sending commands to a live HVAC system :)

**Comment by bbartling** [comment]
This maybe a cool example for the `showcase` to get newbies like myself up and running :)

**Comment by amogorkon** [comment]
I'm glad we got this figured out! Looking forward to hear from you again, I'm very curious what you'll come up with regarding the HVAC👍 

I'll put this into the showcase, good idea.

**Comment by amogorkon** [comment]
Please check the showcase, I added the example. Anything to add?
