### ISSUE TITLE
python 3.9 pip install fuzzylogic

### ISSUE THREAD

**Issue by bbartling** [amogorkon/fuzzylogic#7]
Things are getting messy so I thought I would be put python 3.9 on another issue.

I ran into some sort of numpy issue and had to dumb down numpy to 1.19.2 with `pip install numpy==1.19.2` to even install numpy on vanilla python 3.9

Anyway pip installed `combinators` too.

Seems like I get the same error as python 3.8 on the other git issue using anaconda.

```
>>> 
= RESTART: C:\Users\bbartling\OneDrive - Slipstream\Desktop\fuzzyStuff\test_new.py
Traceback (most recent call last):
  File "C:\Users\bbartling\OneDrive - Slipstream\Desktop\fuzzyStuff\test_new.py", line 1, in <module>
    from fuzzylogic.classes import Domain, Set, Rule
  File "C:\Python39\lib\site-packages\fuzzylogic\classes.py", line 13, in <module>
    from combinators import MAX, MIN, bounded_sum, product, simple_disjoint_sum
ImportError: cannot import name 'MAX' from 'combinators' (C:\Python39\lib\site-packages\combinators\__init__.py)
>>> 
```

```
This is the script:
from fuzzylogic.classes import Domain, Set, Rule
from fuzzylogic.hedges import very

temp = classes.Domain("Temperature", -80, 80)
hum = classes.Domain("Humidity", 0, 100)
motor = classes.Domain("Speed", 0, 2000)

temp.cold = functions.S(0,20)
temp.hot = functions.R(15,30)

hum.dry = functions.S(20,50)
hum.wet = functions.R(40,70)

motor.fast = functions.R(1000,1500)
motor.slow = ~motor.fast

R1 = classes.Rule({(temp.hot, hum.dry): motor.fast})
R2 = classes.Rule({(temp.cold, hum.dry): very(motor.slow)})
R3 = classes.Rule({(temp.hot, hum.wet): very(motor.fast)})
R4 = classes.Rule({(temp.cold, hum.wet): motor.slow})

Rules = classes.Rule({(temp.hot, hum.dry): motor.fast,
                      (temp.cold, hum.dry): very(motor.slow),
                      (temp.hot, hum.wet): very(motor.fast),
                      (temp.cold, hum.wet): motor.slow,
                      })

Rules == R1 | R2 | R3 | R4 == sum([R1, R2, R3, R4])

print(Rules(hum(30), temp(9)))
```

Thanks Anselm no rush!

**Comment by amogorkon** [comment]
I made all imports relative, which should fix this issue. I released a new version on pypi, you can try to pip install it (it works for me like this on a fresh Lubuntu VM with python 3.9).

**Comment by bbartling** [comment]
Hi Anselm 

So I upgraded to 1.0.1, could this be an issue running on Windows?

Ultimately hopefully near term future I will be trying to use this on Linux on a real world type test bench.

When I run the code I get an error in py39 on Windows:
```
Traceback (most recent call last):
  File "C:\Users\bbartling\OneDrive - Slipstream\Desktop\fuzzyStuff\test_new.py", line 4, in <module>
    temp = classes.Domain("Temperature", -80, 80)
NameError: name 'classes' is not defined
```

**Comment by amogorkon** [comment]
Hey Ben,
what's the code you were running?
